# Dependencies
gems: [jekyll-assets, jekyll-sitemap]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aiden Haak
url:              http://www.aidenhaak.com
baseurl:          /

disqus_shortname: aidenhaak
ga_key:		  'UA-XXXXX-X'

author:
  name:           'Aiden Haak'
  email:          ah@aidenhaak.com
  twitter:        https://twitter.com/aidenhaak
  github:         https://github.com/aidenhaak

paginate:         3

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/javascript
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
